### ISSUE TITLE
How does it handle this type of CSV 

### ISSUE THREAD

**Issue by akash3456** [cellaphin/CsvReader#2]
Hi 

Im having issues trying to read a csv using your library,

when using this type of input

"data1","data2","data"

Columnheader;ColumnHeader2;Columnheader3

i get unable to find ColumnHeader, 

im passing in a Delimiter for the semicolon but it blows up trying to read this. 

Any Guidance would be great.

**Comment by OgOfficeChair** [comment]
Hi Akash,

The error "Unable to find column for \"{header}\""" is likely thrown for 2 reasons:

1. The columnsToRead values passed into the CsvReader don't match the column headings in the file. (The columnsToRead values are case sensitive)
2. There's a delimiter ("," or ";") in one of your header fields that is throwing off the mapping.

Let me know if either of these is the issue. If it's not, please provide a sample dataset that causes the error to be thrown

**Comment by OgOfficeChair** [comment]
Akash,

I've verified that the package does handle data for:
```
header1;header2
datarow1,datarow2
```
you may want to verify that your csvreader is initialized like the following, noting the two delimiters being registered:
```
    CsvReader<Person> reader = new(
        fullPath: filePath,
        columnsToRead: new string[] { "FirstName", "MiddleName", "LastName" },
        mapper: new PersonMapper(),
        new string[] { ",", ";" }
    );
```

In the case that your field headings didn't match what was set up in the mapping class, I've updated the RowMapper so that the mappings are case insensitive in v6.0.1. I hope this helps!

If you're still experiencing issues after verifying this, feel free to open another issue.
